name: gwentboard
description: Gwent board score tracker.
publish_to: "none"
version: 1.0.0+2

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  assorted_layout_widgets: ^7.0.0
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  flex_color_scheme: ^6.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  fluttertoast: ^8.0.9
  wakelock: ^0.6.2
  weather_icons: ^3.0.0

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.2.8
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/

# flutter pub run flutter_launcher_icons:main
flutter_icons:
  android: launcher_icon
  ios: true
  image_path: assets/launcher.png

# flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#57859d"
  image: assets/launcher.png
  android: true
  ios: true
  web: true
  android12: true
